#!/bin/csh -f
#TEST-PROGRAM sander
#TEST-DESCRIP TO_BE_DEtermined
#TEST-PURPOSE regression, basic
#TEST-STATE   undocumented

set sander = "${AMBERHOME}/bin/pmemd"

if( $?TESTsander ) then
   set sander = $TESTsander
endif

if( ! $?DO_PARALLEL ) then
        setenv DO_PARALLEL " "
endif

set output = mdout

cat > mdin <<EOF
#short MD run
&cntrl
  imin = 0, nstlim = 10, dt = 0.001,
  irest = 1, ntx = 5, ig = 9999,
  temp0 = 298.0,
  ntc = 2, ntf = 2, tol = 0.00001,
  tautp = 1.0,
  ntwx = 1, ntwe = 0, ntwr = 1, ntpr = 1,
  cut = 8.0, iwrap = 1,
  ntt =1, ntb = 1, ntp = 0,
  nscm = 1000,
  ioutfm=1, ntxo=2,
/
EOF

$DO_PARALLEL $sander -O -i mdin -c inpcrd -o $output < /dev/null || goto error
if ( `basename $sander` == "pmemd.mic_offload.MPI" ) then
../dacdif -r 1.e-05 $output.save $output
else
../dacdif -r 1.e-06 $output.save $output
endif
/bin/rm -f mdin restrt mdinfo mdcrd
exit(0)

error:
echo "  ${0}:  Program error"
exit(1)


